runtime: nodejs18
env: flex

env_variables:
  NODE_ENV: "production"
  TYPESCRIPT_SUPPORT: "true"
  NODE_OPTIONS: "--max_old_space_size=4096"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

build:
  dependencies:
    - name: "nodejs"
      version: "18"
    - name: "typescript"
      version: "5.0.0"  # Specify TypeScript version
  config:
    typescript:
      enabled: true