name: laudspeaker
services:
  - name: api
    github:
      branch: staging
      deploy_on_push: true
      repo: your-repo/laudspeaker
    build_command: npm run build:server
    run_command: npm run start:prod
    env: node
    runtime: nodejs:18
    instance_count: 1
    instance_size_slug: basic-xxs
    healthcheck:
      http_path: /login
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3
    environment:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096

  - name: client
    build_command: npm run build:client
    env: static
    runtime: nodejs:18
    output_dir: packages/client/build
    routes:
      - path: /
    source_dir: packages/client
    environment:
      - key: NODE_ENV
        value: production

databases:
  - name: laudspeaker-db
    engine: PG
    version: "16"