name: laudspeaker
services:
  - name: api
    github:
      branch: staging
      deploy_on_push: true
      repo: your-repo/laudspeaker
    build_command: |
      npm ci
      NODE_OPTIONS=--max_old_space_size=4096 npm run build:server
    run_command: npm run start:prod
    environment_slug: nodejs
    envs:
      - key: NODE_ENV
        value: production
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    source_dir: packages/server
    build_filter:
      paths:
        - packages/server/**
        - package.json
        - package-lock.json
    runtime: nodejs:18

  - name: client
    build_command: |
      npm ci
      NODE_OPTIONS=--max_old_space_size=4096 npm run build:client
    environment_slug: static
    output_dir: packages/client/build
    routes:
      - path: /
    source_dir: packages/client
    build_filter:
      paths:
        - packages/client/**
        - package.json
        - package-lock.json