name: laudspeaker
services:
  - name: api
    github:
      branch: staging
      deploy_on_push: true
      repo: your-repo/laudspeaker
    dockerfile_path: Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    healthcheck:
      http_path: /login
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3

  - name: client
    build_command: |
      npm ci
      NODE_OPTIONS=--max_old_space_size=4096 npm run build:client
    environment_slug: static
    output_dir: packages/client/build
    routes:
      - path: /
    source_dir: packages/client
    build_filter:
      paths:
        - packages/client/**
        - package.json
        - package-lock.json

databases:
  - name: laudspeaker-db
    engine: PG
    version: "16"