name: laudspeaker
services:
  - name: web
    github:
      branch: staging
      deploy_on_push: true
      repo: your-repo/laudspeaker
    build_command: |
      npm install
      npm run build:server
      npm run build:client
    run_command: npm run start:prod
    environment_slug: nodejs
    env_vars:
      - key: NODE_ENV
        value: production
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    source_dir: /
    static_sites:
      - name: client
        environment_slug: nodejs
        build_command: npm run build:client
        output_dir: packages/client/build
        routes:
          - path: /
    jobs:
      - name: migrations
        run_command: npm run migrations
        github:
          branch: staging
          deploy_on_push: true
          repo: your-repo/laudspeaker