
name: laudspeaker
services:
  - name: web
    github:
      branch: staging
      deploy_on_push: true
      repo: your-repo/laudspeaker
    build_command: npm run build
    run_command: npm run start:prod
    envs:
      - key: NODE_ENV
        value: production
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /