services:
  - type: web
    name: laudspeaker
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    nodeVersion: 18
    healthCheckPath: /login
    dockerfilePath: ./Dockerfile.laudspeaker
    dockerContext: .
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - fromGroup: laudspeaker
      - key: PORT
        value: 80
      - key: SYNCHRONIZE
        value: true
      - key: JWT_KEY
        generateValue: true
      - key: JWT_EXPIRES
        value: 365d
      - key: CH_MIGRATIONS_HOST
        fromService:
          type: pserv
          name: clickhouse
          property: host
      - key: CH_MIGRATIONS_PORT
        value: 8123
      - key: CH_MIGRATIONS_USER
        value: default
      - key: CH_MIGRATIONS_PASSWORD
        value:
      - key: CH_MIGRATIONS_DB
        value: default
      - key: CH_MIGRATIONS_HOME
        value: packages/server/src/migrations/clickhouse
      - key: MONGOOSE_URL
        fromService:
          type: pserv
          name: mongo
          property: hostport
      - key: CLICKHOUSE_HOST
        fromService:
          type: pserv
          name: clickhouse
          property: hostport
      - key: REDIS_HOST
        fromService:
          type: redis
          name: laudspeaker
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: laudspeaker
          property: port
      - key: DATABASE_USER
        fromDatabase:
          name: laudspeaker-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: laudspeaker-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: laudspeaker-db
          property: host
      - key: DATABASE_NAME
        fromDatabase:
          name: laudspeaker-db
          property: database
      - key: NODE_OPTIONS
        value: "--max_old_space_size=4096"
      - key: TYPESCRIPT_SUPPORT
        value: "true"

  - type: web
    name: laudspeaker-api
    env: node
    region: oregon
    buildCommand: npm ci && npm run build:server
    startCommand: npm run start:prod
    nodeVersion: 18.x
    envVars:
      - fromGroup: laudspeaker
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
      # ...existing code for other env vars...

  - type: web
    name: laudspeaker-client
    env: static
    buildCommand: npm ci && npm run build:client
    staticPublishPath: packages/client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: redis
    name: laudspeaker
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

  - type: pserv
    name: clickhouse
    env: docker
    dockerfilePath: ./Dockerfile.clickhouse
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10

  - type: pserv
    name: mongo
    env: docker
    dockerfilePath: ./Dockerfile.mongo
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10

databases:
  - name: laudspeaker-db
